language: node_js
node_js: stable

install: true

branches:
  only:
  - master

env:
 global:
   - GH_REF: github.com/892768447/cdn.git

before_script:
- git config --global user.name "Irony"
- git config --global user.email "892768447@qq.com"

script:
- git push -f https://${GH_TOKEN}@${GH_REF} `npm version patch -m "%s [ci skip]"`
- git push -f https://${GH_TOKEN}@${GH_REF} HEAD:master